#!/bin/sh
# Enforce author/committer identity as cocowutech
GIT_AUTHOR_NAME="RONG WU"
GIT_AUTHOR_EMAIL="cocowutech@users.noreply.github.com"
GIT_COMMITTER_NAME="RONG WU"
GIT_COMMITTER_EMAIL="cocowutech@users.noreply.github.com"
export GIT_AUTHOR_NAME GIT_AUTHOR_EMAIL GIT_COMMITTER_NAME GIT_COMMITTER_EMAIL
